cmds.nParticle( ll=[-0.2,5,-0.2], ur=[0.2,100,0.2], grs=0.2)
cmds.select('nParticleShape1')
cmds.setAttr('nParticleShape1.radius', 0.1)
cmds.setAttr('nParticleShape1.enableSPH', 1)
cmds.setAttr('nParticleShape1.selfCollide', 0)
cmds.setAttr('nParticleShape1.particleRenderType', 7)
cmds.setAttr('nParticleShape1.surfaceTension', 1)

cmds.setAttr('nParticleShape1.incompressibility', 3)
cmds.setAttr('nParticleShape1.viscosity', 0.01)
cmds.setAttr('nParticleShape1.radiusScaleSPH', 0.8)
cmds.setAttr('nParticleShape1.friction', 0.1)
cmds.setAttr('nParticleShape1.maxSelfCollisionIterations', 10)
cmds.setAttr('nParticleShape1.restDensity', 2.5)